title: Daesung's blog
description: Daesung's blog

url: https://dskim10.github.io/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: Contact
    url: /contact

social:
  github: brianmaierjr
  twitter: brianmaierjr
  facebook: brianmaierjr
  email: dskim10@gmail.com

google_analytics: "UA-58263416-1"
